# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShotEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentrepository',
            old_name='department',
            new_name='departmentName',
        ),
    ]
